### PR TITLE
Add automatic translation tool

### PR DESCRIPTION
**Pull request by 13steinj**
With use of russian since I don't have a russian keyboard and my time would be better off making an automatic tool for ya :D; you'll need to `pip3 install selenium`. Python because my java is rusty >.>

### CODE REVIEW

**Comment by 13steinj** [comment]
Also it's good to mention that it *is* possible to translate strings with % in them, just that would take more time to do since a sub class of str would need to be made; then the index of % calculated and stripped, the string translated, and then the % reinserted.

**Comment by Pokechu22** [comment]
Looks pretty nice!  Just a few comments.

* Can you manually check the contents of the file, if you haven't already?  Automatic translation can be a bit wonky.
* The translated by comment was supposed to be in the target language - it's displayed with the rest of the text on the about page.
* Strings containing `%n` can probably automatically be translated, by replacing all instances of `%n` with a real newline when giving it to google and then reversing that process afterwards.
* The translation script probably shouldn't be in the language assets folder - that folder is packed into the mod zip.  Although that doesn't really matter _too_ much and I'm not sure what a better place for it would be.

**Comment by Pokechu22** [comment]
Also, whenever I see the phrase `webdriver`, I think of [webdriver torso](https://www.youtube.com/results?search_query=webdriver+torso).  If I'm understanding it right, selenium webdriver basically simulates a browser?

**Comment by 13steinj** [comment]
* Will do as soon as i can
* you mean the translatorCredit?
* Will make the newline change as soon as I can
* maybe <toplevel>/py/langconvert.py?

What the fuck did I just click >.>?

Close. selenium is the main package, but nothing is useful without selenium's webdrivers. A webdriver in selenium instantiates the actual webdriver executable; which allows for direct interaction with a webbrowser.

PhantomJS and Firefox are browsers that already come with their webdriver executable preinstalled.

For chrome, ie, and some others, you'll get an error when the webdriver instance is trying to be made with a url to where you can download the webdriver executable, afterwhich, place that executable somewhere in your PATH and then it will work fine.

Like mentioned in the commit, Firefox is recommended for viewing since it already comes with it's webdriver executable preinstalled; otherwise PhantomJS is recommended since it technically goes slightly faster since there is no time wasted on rendering the page, which you can download / get the source from [here](http://phantomjs.org/download.html)

**Comment by Pokechu22** [comment]
Yep, referring to translatorCredit.

Perhaps `/util/langconvert.py` or maybe `/scripts/langconvert.py`?  Actually, `/scripts/langconvert.py` would work well - I could move the existing `createSymLinks` scripts to that folder as well.

**Comment by 13steinj** [comment]
Sure thing; will make the changes / look over as soon as I can (webdriver executables can't be properly added to my path on windows since my path is too large, so the only places where I can test is in my vm which takes forever to boot up and at work; where I'm not supposed to do side projects >.<)

**Comment by Pokechu22** [comment]
Probably won't be able to get this in for the immediate next release (which _hopefully_ will come out today).  Though I think I'll probably end up with a second release relatively soon after.

**Comment by Pokechu22** [comment]
Also, have you considered temporarily running `path [new path]` before running the scripts so that they can be on the path without permanently changing the path?  It might be possible to get that to work.

**Comment by 13steinj** [comment]
@Pokechu22 I just had my time freed up to address the issues. I'm looking at the translations now, but what do you mean about `path [new path]` (/ why would you need it on the system variable path in the first place)?

**Comment by Pokechu22** [comment]
I was suggesting that in regards to 

> webdriver executables can't be properly added to my path on windows since my path is too large

I thought that you meant that the environment variable `%PATH%` was too large to add anything else (seems plausible).

**Comment by 13steinj** [comment]
Oh. No, but I'll try; thanks for the tip :P. Didn't know that could be done
on windows, I was only familiar with the `export` based syntax on linux

**Comment by Pokechu22** [comment]
I'm probably going to release this sunday - if you're not done by then I'll probably add this in in the release after that (I expect there will probably be a second release soon after).

**Comment by 13steinj** [comment]
I'm almost done checking the translations, but I don't think I'll be able to automatically handle the % and special § strings until later (it entails subclassing str and using regex to find, split, and reenter on those chars, which is proving difficult).

**Comment by Pokechu22** [comment]
One final thing to know - if you want to test out the translations in-game, you can do so with a resource pack (if you update to 1.8d).  [Here's how if you need some info](https://github.com/Pokechu22/WorldDownloader/wiki/how-to-help-translate#testing-translations).

**Comment by 13steinj** [comment]
I wanted to not comment until I can actually test; but I have a little bit of a problem: my VM where I edited the files crashed mid-run because my security software decided to read the virtual hard drive file (Thanks so much ZoneAlarm). I've been editing all my repos from my phone; which is a bit of a hassle.

Once I fix my vm / manage to get the files out via mounting the drive (which should hopefully work); I'll update the branch and test the translations in-game. Sorry for uh, having this take literally a month at this point when it should have taken around half that.

**Comment by Pokechu22** [comment]
Fair enough.  I'm familiar with VM troubles :P

**Comment by Pokechu22** [comment]
Can you push any of the changes you have locally and rebase?  Not too worried about having this perfect since I can move stuff myself later but I would like to get this merged eventually.

**Pull request closed without merging**
