### PR TITLE
Remove memory that's not needed

### PR DESCRIPTION
**Pull request by jascotty2**
Remove chunks from cache when writing.
Also, mcProfiler seems to eat up memory over time.

### CODE REVIEW

**Comment by Pokechu22** [comment]
Clearing those maps does seem like a good idea, :+1:

I'm a bit skeptical as to whether the entity one is correct to clear (entity saving is a bit strange and I've been meaning to investigate it).  The case where it applies is when move away from it, the entities in the chunk are untracked and removed from the client; entities are stored in there so that they're saved when the chunk is unloaded later.  But if the chunk is then reloaded and unloaded again without tracking the entities, they can simply be retrieved from the map.  Though actually, that code seems broken in another way (it'll put the same entity in the map multiple times I think), so simply getting rid of it for now seems reasonable.

Block entities are imported from the saved chunk, so it's definitely fine to clear it.

-----

It seems odd for the profiler to be the culprit.  Stuff is only added to any of the maps when profiling is enabled -- i.e. the shift+f3 pie chart is opened.  At least, that's the case for vanilla.  It does look like it can leak memory though; it's also only cleared when profiling is started (instead of stopped): `Minecraft.runGameLoop`:

```java
		if (this.gameSettings.showDebugInfo && this.gameSettings.showDebugProfilerChart && !this.gameSettings.hideGUI) {
			if (!this.mcProfiler.profilingEnabled) {
				this.mcProfiler.clearProfiling();
			}

			this.mcProfiler.profilingEnabled = true;
			this.displayDebugInfo(i1);
		} else {
			this.mcProfiler.profilingEnabled = false;
			this.prevFrameTime = System.nanoTime();
		}
```

Since the profiling is sometimes useful, I'd ideally like to leave that code in.  Are you sure that it's actually causing problems when the profiler isn't enabled?

**Comment by jascotty2** [comment]
Yes; I started with disabling the profiler, but still had the memory problems, so added the function to clear out memory that wasn't needed for the chunks, and didn't have any more issues then.
To test to see if that was the sole source of the issue, I re-enabled the profiler code and tested again. After only 10 minutes, it was up to 430,000 Hashmap Nodes that could not be garbage-collected.
(The code without the profiler I tested for 20 minutes and only had about 130,000)

**Comment by Pokechu22** [comment]
Hm, and did you have the profiler open at that time?  Or was it closed?

**Comment by jascotty2** [comment]
I did not open the profiler menu for either run

If you'd like to test it yourself, I've been using VisualVM (I'm sure there are better ones, but it does what I was looking for)

**Comment by Pokechu22** [comment]
Hm.  I haven't used VisualVM much, and am trying to figure it out.  But if I take a heap dump, enter "Profiler" on the classes tab, and then look at the instances (there's 2, one for the client and one for the integrated singleplayer server), both have `profilingMap`, `timestampList`, `sectionList` all with size 0 even without this change.  But I'll keep testing, and hopefully I'll be able to reproduce it.

**Comment by Pokechu22** [comment]
Manually comparing the heap dumps, I see 871 entries in `WDL.newEntities` without this change (current `v4` branch), and 0 with this change; that's expected and good.  The newTileEntities map is empty, since I didn't open any chests/otherwise save any entities.  Seems reasonable.  I'm displaying them with the "Static Fields" option on the classes tab.

I can confirm the reduced number of `HashMap` instances with the profiler enabled/disabled, though I didn't actually run for that long.  It's a difference of ~16k instances, or about 6 retained megabytes (i.e. not eligible for garbage collection as far as I can tell).  The full change saves ~45k instances, or ~20 retained megabytes.  Still, I'm not entirely sure where these instances are actually stored, and I can't find a good way to determine in bulk the locations of them (I can check any individual one I want, but 45 thousand is too many to do this in a useful manner).

I'm still not sure _why_ the profiler is making a difference, or even if it actually is and this isn't just a confirmation bias.  But I'm experiencing it too...

**Comment by Pokechu22** [comment]
I did a fairly simple control test where I launched the game and downloaded without moving; doing that there isn't any difference with this fix so it _is_ actually helping in the case where you move.

**Comment by Tsoccerguy3** [comment]
not downloading some entities like Statues and map data in frames , Holograms produced from command block. maybe more stuff . Stutter is almost gone

**Comment by Pokechu22** [comment]
Statues being armor stands?  Hm.  I think it's possible that the entity code might be broken in other ways, going to need to look into it (since you mentioned they didn't work before the change either).

**Comment by Tsoccerguy3** [comment]
Yes , posed armor stands with a head and clothes (statues) . lol .

**Comment by Pokechu22** [comment]
Created #78 for that.

Also, as another note, I realized why removing entities would lead to a decrease in hashmaps and lists.  Entities have a `riddenByEntities` list, and also their `dataManager` (which contains a HashMap).  But they also reference the world they were in, even if the world has been changed otherwise.  That'd definitely prevent some things from being collected...

**Comment by Pokechu22** [comment]
I haven't been able to figure out why the profiler is making a performance improvement, but in all of my testing (even in a very controlled setup) it has had the same improvement.  So, merging, and then I'll make some minor cleanup.

**Comment by Pokechu22** [comment]
Merged and some small cleanup applied (profiler is conditionally enabled instead of commented out completely, but the effect is the same).  Thanks for the pull request!

**Pull request merged**
